language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_scripts:
  - composer install --prefer-source --no-interaction --dev

before_install:
  - travis_retry composer self-update

script: vendor/bin/phpunit