language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache

before_scripts:
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit